# Generated by Django 3.2.12 on 2022-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
