# Generated by Django 3.2.12 on 2022-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted'), ('R', 'Rejected'), ('P', 'Published'), ('A', 'Archived')], default='D', max_length=1),
        ),
    ]
