# Generated by Django 3.2.12 on 2022-02-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('Dar', 'Draft'), ('Sub', 'Submitted'), ('Rej', 'Rejected'), ('Pub', 'Published'), ('Arc', 'Archived')], default='Dar', max_length=3),
        ),
    ]
