# Generated by Django 3.2.12 on 2022-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('DRT', 'Draft'), ('SUB', 'Submitted'), ('REJ', 'Rejected'), ('PUB', 'Published'), ('ARC', 'Archived')], default='Dar', max_length=3),
        ),
    ]
