# Generated by Django 3.2.12 on 2022-02-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.CharField(choices=[('POP', 'Popular'), ('TRD', 'Trending'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('DRT', 'Draft'), ('SUB', 'Submitted'), ('REJ', 'Rejected'), ('PUB', 'Published'), ('ARC', 'Archived')], default='DRT', max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
